
x-airflow-env: &airflow-env
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
  AIRFLOW__CORE__AUTH_MANAGER: ${AIRFLOW_AUTH_MANAGER}
  AIRFLOW_HOME: /opt/airflow
  PYTHONPATH: /opt/airflow/repo
  DBT_PROFILES_DIR: /opt/airflow/dbt/.dbt
  DBT_TARGET: container
  # metadata DB (used by Airflow itself)
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_AIRFLOW_DB}
  # Make the web URL consistent with host port
  AIRFLOW__WEBSERVER__BASE_URL: ${AIRFLOW_BASE_URL}
  # App DB envs (for your DAGs/dbt)
  POSTGRES_HOST: ${PG_HOST}
  POSTGRES_PORT: "${PG_PORT}"
  POSTGRES_DB: ${PG_APPDB}
  POSTGRES_USER: ${PG_USER}
  POSTGRES_PASSWORD: ${PG_PASSWORD}

services:
  postgres:
    image: postgres:15
    container_name: priceradar-db
    ports: ["${PG_PORT}:5432"]
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_APPDB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_APPDB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  airflow-image:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: priceradar-airflow:latest
    container_name: priceradar-airflow-image
    entrypoint: ["bash","-lc","sleep 1"]
    depends_on:
      postgres:
        condition: service_healthy

  airflow-init:
    image: priceradar-airflow:latest
    container_name: priceradar-airflow-init
    entrypoint: ["/bin/bash","-lc"]
    command: ./scripts/bootstrap-airflow.sh
    environment:
      <<: *airflow-env
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_AIRFLOW_DB: ${PG_AIRFLOW_DB}
      AIRFLOW_ADMIN_USERNAME: ${AIRFLOW_ADMIN_USERNAME}
      AIRFLOW_ADMIN_PASSWORD: ${AIRFLOW_ADMIN_PASSWORD}
      AIRFLOW_ADMIN_EMAIL: ${AIRFLOW_ADMIN_EMAIL}
      AIRFLOW_ADMIN_FIRST: ${AIRFLOW_ADMIN_FIRST}
      AIRFLOW_ADMIN_LAST: ${AIRFLOW_ADMIN_LAST}
    volumes:
      - ./scripts:/opt/airflow/scripts:ro
      - ./airflow_dags:/opt/airflow/dags
      - ./dbt/priceradar_dbt:/opt/airflow/dbt/priceradar_dbt
      - ./dbt/.dbt:/opt/airflow/dbt/.dbt
      - ./:/opt/airflow/repo
      - airflow_logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy

  airflow-webserver:
    image: priceradar-airflow:latest
    container_name: priceradar-airflow-webserver
    command: api-server
    environment:
      <<: *airflow-env
    ports: ["${AIRFLOW_PORT}:8080"]
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - ./dbt/priceradar_dbt:/opt/airflow/dbt/priceradar_dbt
      - ./dbt/.dbt:/opt/airflow/dbt/.dbt
      - ./:/opt/airflow/repo
      - airflow_logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      airflow-image:
        condition: service_started
    restart: unless-stopped

  airflow-scheduler:
    image: priceradar-airflow:latest
    container_name: priceradar-airflow-scheduler
    command: scheduler
    environment:
      <<: *airflow-env
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - ./dbt/priceradar_dbt:/opt/airflow/dbt/priceradar_dbt
      - ./dbt/.dbt:/opt/airflow/dbt/.dbt
      - ./:/opt/airflow/repo
      - airflow_logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
      airflow-image:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
  airflow_logs: